language: python
python:
  - '2.6'
  - '2.7'
before_install:
  - sudo apt-get install python-psycopg2 python-pywcs python-matplotlib python-numpy
install:
  - pip install -r requirements.txt --use-mirrors
script:
  - touch bananaproject/settings/local.py
  - ./manage.py test --settings=testing.settings
branches:
  only:
    - master
