language: python
python:
  - "2.6"
  - "2.7"
before_install: sudo apt-get install python-psycopg2 pywcs python-matplotlib python-numpy
install: "pip install -r requirements.txt --use-mirrors"
script:
  - cp bananaproject/settings/local_example.py bananaproject/settings/local.py
  - ./manage.py test --settings=bananaproject.settings.testing

